apiVersion: apps/v1
kind: Deployment
metadata:
  name: flatbuddy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flatbuddy
  template:
    metadata:
      labels:
        app: flatbuddy
    spec:
      containers:
        - name: flatbuddy
          image: flatbuddy-service:latest
          imagePullPolicy: Never  # Prevent Kubernetes from pulling the image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flatbuddy-service
spec:
  type: NodePort
  selector:
    app: flatbuddy
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
