apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports
  template:
    metadata:
      labels:
        app: reports
    spec:
      containers:
        - name: reports
          image: reports-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: USER_SERVICE_URL
              value: http://flatbuddy-service:8080
            - name: FLAT_SERVICE_URL
              value: http://flatbuddy-service:8080
---
apiVersion: v1
kind: Service
metadata:
  name: reports-service
spec:
  type: NodePort
  selector:
    app: reports
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081